### ISSUE TITLE
缺失 Linux 平台上正常启动所需的补丁 LinuxLauncher.sh

### ISSUE THREAD

**Issue by Liarscake** [imgradeone/DDLCModTemplate-Chinese-next#8]
rt(
若不使用 LinuxLauncher.sh 会触发 import 问题：
```
Could not import renpy.bootstrap. Please ensure you decompressed Ren'Py
correctly, preserving the directory structure.
Traceback (most recent call last):
  File "/home/PartyParrot/Projects/OldMemories-1.0-dists/DDLC-1.1.1-pc/lib/linux-x86_64/../../OldMemories.py", line 198, in <module>
    main()
  File "/home/PartyParrot/Projects/OldMemories-1.0-dists/DDLC-1.1.1-pc/lib/linux-x86_64/../../OldMemories.py", line 188, in main
    import renpy.bootstrap
  File "/home/PartyParrot/Projects/OldMemories-1.0-dists/DDLC-1.1.1-pc/renpy/__init__.py", line 56, in <module>
    from renpy.compat import *
  File "/home/PartyParrot/Projects/OldMemories-1.0-dists/DDLC-1.1.1-pc/renpy/compat/__init__.py", line 59, in <module>
    import future.standard_library
ImportError: No module named future.standard_library

```

**Comment by imgradeone** [comment]
已补充 https://github.com/imgradeone/DDLCModTemplate-Chinese-next/commit/0f1830b6862b43255fe0c08619d66bcff029eaf9
